Repository vuejs/vue-router, pull requests merged in 2020-05, with the labels that each got.

#1814 feat(scroll): use manual scrollRestoration with scrollBehavior
  src/util/scroll.js
Labels: improvement

#2497 feat(types): NavigationGuardNext
  types/index.d.ts
  types/router.d.ts
Labels: Typescript

#2292 feat(url): call afterEach hooks after url is ensured
  src/history/base.js
Labels: feature request
